//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WinControlServer.examService {
    using System.Data;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="examService.ExamServiceSoap")]
    public interface ExamServiceSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string HelloWorld();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetExamineeIdentityInfo", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable GetExamineeIdentityInfo(string sfzhm);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetYYInfo", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string GetYYInfo(string KTType, string cardno);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetKSInif", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string GetKSInif(string KTType, string KTno);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AddEvaluatData", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string AddEvaluatData(string callip, string sfzh, string callnum, string callxh, string evavalue);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ExamServiceSoapChannel : WinControlServer.examService.ExamServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ExamServiceSoapClient : System.ServiceModel.ClientBase<WinControlServer.examService.ExamServiceSoap>, WinControlServer.examService.ExamServiceSoap {
        
        public ExamServiceSoapClient() {
        }
        
        public ExamServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ExamServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ExamServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ExamServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string HelloWorld() {
            return base.Channel.HelloWorld();
        }
        
        public System.Data.DataTable GetExamineeIdentityInfo(string sfzhm) {
            return base.Channel.GetExamineeIdentityInfo(sfzhm);
        }
        
        public string GetYYInfo(string KTType, string cardno) {
            return base.Channel.GetYYInfo(KTType, cardno);
        }
        
        public string GetKSInif(string KTType, string KTno) {
            return base.Channel.GetKSInif(KTType, KTno);
        }
        
        public string AddEvaluatData(string callip, string sfzh, string callnum, string callxh, string evavalue) {
            return base.Channel.AddEvaluatData(callip, sfzh, callnum, callxh, evavalue);
        }
    }
}
