//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace QueuingSystem.LHYserver {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="DynamicInterfaceService", ConfigurationName="LHYserver.WebServiceSoap")]
    public interface WebServiceSoap {
        
        // CODEGEN: 命名空间 DynamicInterfaceService 的元素名称 dwjgdm 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="DynamicInterfaceService/GetBAXX", ReplyAction="*")]
        QueuingSystem.LHYserver.GetBAXXResponse GetBAXX(QueuingSystem.LHYserver.GetBAXXRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="DynamicInterfaceService/GetBAXX", ReplyAction="*")]
        System.Threading.Tasks.Task<QueuingSystem.LHYserver.GetBAXXResponse> GetBAXXAsync(QueuingSystem.LHYserver.GetBAXXRequest request);
        
        // CODEGEN: 命名空间 DynamicInterfaceService 的元素名称 dwjgdm 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="DynamicInterfaceService/SetBXQH", ReplyAction="*")]
        QueuingSystem.LHYserver.SetBXQHResponse SetBXQH(QueuingSystem.LHYserver.SetBXQHRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="DynamicInterfaceService/SetBXQH", ReplyAction="*")]
        System.Threading.Tasks.Task<QueuingSystem.LHYserver.SetBXQHResponse> SetBXQHAsync(QueuingSystem.LHYserver.SetBXQHRequest request);
        
        // CODEGEN: 命名空间 DynamicInterfaceService 的元素名称 dwjgdm 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="DynamicInterfaceService/SetPJXX", ReplyAction="*")]
        QueuingSystem.LHYserver.SetPJXXResponse SetPJXX(QueuingSystem.LHYserver.SetPJXXRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="DynamicInterfaceService/SetPJXX", ReplyAction="*")]
        System.Threading.Tasks.Task<QueuingSystem.LHYserver.SetPJXXResponse> SetPJXXAsync(QueuingSystem.LHYserver.SetPJXXRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetBAXXRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetBAXX", Namespace="DynamicInterfaceService", Order=0)]
        public QueuingSystem.LHYserver.GetBAXXRequestBody Body;
        
        public GetBAXXRequest() {
        }
        
        public GetBAXXRequest(QueuingSystem.LHYserver.GetBAXXRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="DynamicInterfaceService")]
    public partial class GetBAXXRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string dwjgdm;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string dwmc;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string yhbs;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string yhxm;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string sbkzjsjip;
        
        public GetBAXXRequestBody() {
        }
        
        public GetBAXXRequestBody(string dwjgdm, string dwmc, string yhbs, string yhxm, string sbkzjsjip) {
            this.dwjgdm = dwjgdm;
            this.dwmc = dwmc;
            this.yhbs = yhbs;
            this.yhxm = yhxm;
            this.sbkzjsjip = sbkzjsjip;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetBAXXResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetBAXXResponse", Namespace="DynamicInterfaceService", Order=0)]
        public QueuingSystem.LHYserver.GetBAXXResponseBody Body;
        
        public GetBAXXResponse() {
        }
        
        public GetBAXXResponse(QueuingSystem.LHYserver.GetBAXXResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="DynamicInterfaceService")]
    public partial class GetBAXXResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetBAXXResult;
        
        public GetBAXXResponseBody() {
        }
        
        public GetBAXXResponseBody(string GetBAXXResult) {
            this.GetBAXXResult = GetBAXXResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SetBXQHRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SetBXQH", Namespace="DynamicInterfaceService", Order=0)]
        public QueuingSystem.LHYserver.SetBXQHRequestBody Body;
        
        public SetBXQHRequest() {
        }
        
        public SetBXQHRequest(QueuingSystem.LHYserver.SetBXQHRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="DynamicInterfaceService")]
    public partial class SetBXQHRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string dwjgdm;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string dwmc;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string yhbs;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string yhxm;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string ywckjsjip;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string sbkzjsjip;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string qhxxxlh;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string pdh;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=8)]
        public string ywlb;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=9)]
        public string sfzmhm;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=10)]
        public string dlrsfzmhm;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=11)]
        public string qhrxm;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=12)]
        public string qhsj;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=13)]
        public string rylb;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=14)]
        public string jbr;
        
        public SetBXQHRequestBody() {
        }
        
        public SetBXQHRequestBody(string dwjgdm, string dwmc, string yhbs, string yhxm, string ywckjsjip, string sbkzjsjip, string qhxxxlh, string pdh, string ywlb, string sfzmhm, string dlrsfzmhm, string qhrxm, string qhsj, string rylb, string jbr) {
            this.dwjgdm = dwjgdm;
            this.dwmc = dwmc;
            this.yhbs = yhbs;
            this.yhxm = yhxm;
            this.ywckjsjip = ywckjsjip;
            this.sbkzjsjip = sbkzjsjip;
            this.qhxxxlh = qhxxxlh;
            this.pdh = pdh;
            this.ywlb = ywlb;
            this.sfzmhm = sfzmhm;
            this.dlrsfzmhm = dlrsfzmhm;
            this.qhrxm = qhrxm;
            this.qhsj = qhsj;
            this.rylb = rylb;
            this.jbr = jbr;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SetBXQHResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SetBXQHResponse", Namespace="DynamicInterfaceService", Order=0)]
        public QueuingSystem.LHYserver.SetBXQHResponseBody Body;
        
        public SetBXQHResponse() {
        }
        
        public SetBXQHResponse(QueuingSystem.LHYserver.SetBXQHResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="DynamicInterfaceService")]
    public partial class SetBXQHResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string SetBXQHResult;
        
        public SetBXQHResponseBody() {
        }
        
        public SetBXQHResponseBody(string SetBXQHResult) {
            this.SetBXQHResult = SetBXQHResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SetPJXXRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SetPJXX", Namespace="DynamicInterfaceService", Order=0)]
        public QueuingSystem.LHYserver.SetPJXXRequestBody Body;
        
        public SetPJXXRequest() {
        }
        
        public SetPJXXRequest(QueuingSystem.LHYserver.SetPJXXRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="DynamicInterfaceService")]
    public partial class SetPJXXRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string dwjgdm;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string dwmc;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string yhbs;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string yhxm;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string qhxxxlh;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string pjlb;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string pjjg;
        
        public SetPJXXRequestBody() {
        }
        
        public SetPJXXRequestBody(string dwjgdm, string dwmc, string yhbs, string yhxm, string qhxxxlh, string pjlb, string pjjg) {
            this.dwjgdm = dwjgdm;
            this.dwmc = dwmc;
            this.yhbs = yhbs;
            this.yhxm = yhxm;
            this.qhxxxlh = qhxxxlh;
            this.pjlb = pjlb;
            this.pjjg = pjjg;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SetPJXXResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SetPJXXResponse", Namespace="DynamicInterfaceService", Order=0)]
        public QueuingSystem.LHYserver.SetPJXXResponseBody Body;
        
        public SetPJXXResponse() {
        }
        
        public SetPJXXResponse(QueuingSystem.LHYserver.SetPJXXResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="DynamicInterfaceService")]
    public partial class SetPJXXResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string SetPJXXResult;
        
        public SetPJXXResponseBody() {
        }
        
        public SetPJXXResponseBody(string SetPJXXResult) {
            this.SetPJXXResult = SetPJXXResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebServiceSoapChannel : QueuingSystem.LHYserver.WebServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebServiceSoapClient : System.ServiceModel.ClientBase<QueuingSystem.LHYserver.WebServiceSoap>, QueuingSystem.LHYserver.WebServiceSoap {
        
        public WebServiceSoapClient() {
        }
        
        public WebServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        QueuingSystem.LHYserver.GetBAXXResponse QueuingSystem.LHYserver.WebServiceSoap.GetBAXX(QueuingSystem.LHYserver.GetBAXXRequest request) {
            return base.Channel.GetBAXX(request);
        }
        
        public string GetBAXX(string dwjgdm, string dwmc, string yhbs, string yhxm, string sbkzjsjip) {
            QueuingSystem.LHYserver.GetBAXXRequest inValue = new QueuingSystem.LHYserver.GetBAXXRequest();
            inValue.Body = new QueuingSystem.LHYserver.GetBAXXRequestBody();
            inValue.Body.dwjgdm = dwjgdm;
            inValue.Body.dwmc = dwmc;
            inValue.Body.yhbs = yhbs;
            inValue.Body.yhxm = yhxm;
            inValue.Body.sbkzjsjip = sbkzjsjip;
            QueuingSystem.LHYserver.GetBAXXResponse retVal = ((QueuingSystem.LHYserver.WebServiceSoap)(this)).GetBAXX(inValue);
            return retVal.Body.GetBAXXResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<QueuingSystem.LHYserver.GetBAXXResponse> QueuingSystem.LHYserver.WebServiceSoap.GetBAXXAsync(QueuingSystem.LHYserver.GetBAXXRequest request) {
            return base.Channel.GetBAXXAsync(request);
        }
        
        public System.Threading.Tasks.Task<QueuingSystem.LHYserver.GetBAXXResponse> GetBAXXAsync(string dwjgdm, string dwmc, string yhbs, string yhxm, string sbkzjsjip) {
            QueuingSystem.LHYserver.GetBAXXRequest inValue = new QueuingSystem.LHYserver.GetBAXXRequest();
            inValue.Body = new QueuingSystem.LHYserver.GetBAXXRequestBody();
            inValue.Body.dwjgdm = dwjgdm;
            inValue.Body.dwmc = dwmc;
            inValue.Body.yhbs = yhbs;
            inValue.Body.yhxm = yhxm;
            inValue.Body.sbkzjsjip = sbkzjsjip;
            return ((QueuingSystem.LHYserver.WebServiceSoap)(this)).GetBAXXAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        QueuingSystem.LHYserver.SetBXQHResponse QueuingSystem.LHYserver.WebServiceSoap.SetBXQH(QueuingSystem.LHYserver.SetBXQHRequest request) {
            return base.Channel.SetBXQH(request);
        }
        
        public string SetBXQH(string dwjgdm, string dwmc, string yhbs, string yhxm, string ywckjsjip, string sbkzjsjip, string qhxxxlh, string pdh, string ywlb, string sfzmhm, string dlrsfzmhm, string qhrxm, string qhsj, string rylb, string jbr) {
            QueuingSystem.LHYserver.SetBXQHRequest inValue = new QueuingSystem.LHYserver.SetBXQHRequest();
            inValue.Body = new QueuingSystem.LHYserver.SetBXQHRequestBody();
            inValue.Body.dwjgdm = dwjgdm;
            inValue.Body.dwmc = dwmc;
            inValue.Body.yhbs = yhbs;
            inValue.Body.yhxm = yhxm;
            inValue.Body.ywckjsjip = ywckjsjip;
            inValue.Body.sbkzjsjip = sbkzjsjip;
            inValue.Body.qhxxxlh = qhxxxlh;
            inValue.Body.pdh = pdh;
            inValue.Body.ywlb = ywlb;
            inValue.Body.sfzmhm = sfzmhm;
            inValue.Body.dlrsfzmhm = dlrsfzmhm;
            inValue.Body.qhrxm = qhrxm;
            inValue.Body.qhsj = qhsj;
            inValue.Body.rylb = rylb;
            inValue.Body.jbr = jbr;
            QueuingSystem.LHYserver.SetBXQHResponse retVal = ((QueuingSystem.LHYserver.WebServiceSoap)(this)).SetBXQH(inValue);
            return retVal.Body.SetBXQHResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<QueuingSystem.LHYserver.SetBXQHResponse> QueuingSystem.LHYserver.WebServiceSoap.SetBXQHAsync(QueuingSystem.LHYserver.SetBXQHRequest request) {
            return base.Channel.SetBXQHAsync(request);
        }
        
        public System.Threading.Tasks.Task<QueuingSystem.LHYserver.SetBXQHResponse> SetBXQHAsync(string dwjgdm, string dwmc, string yhbs, string yhxm, string ywckjsjip, string sbkzjsjip, string qhxxxlh, string pdh, string ywlb, string sfzmhm, string dlrsfzmhm, string qhrxm, string qhsj, string rylb, string jbr) {
            QueuingSystem.LHYserver.SetBXQHRequest inValue = new QueuingSystem.LHYserver.SetBXQHRequest();
            inValue.Body = new QueuingSystem.LHYserver.SetBXQHRequestBody();
            inValue.Body.dwjgdm = dwjgdm;
            inValue.Body.dwmc = dwmc;
            inValue.Body.yhbs = yhbs;
            inValue.Body.yhxm = yhxm;
            inValue.Body.ywckjsjip = ywckjsjip;
            inValue.Body.sbkzjsjip = sbkzjsjip;
            inValue.Body.qhxxxlh = qhxxxlh;
            inValue.Body.pdh = pdh;
            inValue.Body.ywlb = ywlb;
            inValue.Body.sfzmhm = sfzmhm;
            inValue.Body.dlrsfzmhm = dlrsfzmhm;
            inValue.Body.qhrxm = qhrxm;
            inValue.Body.qhsj = qhsj;
            inValue.Body.rylb = rylb;
            inValue.Body.jbr = jbr;
            return ((QueuingSystem.LHYserver.WebServiceSoap)(this)).SetBXQHAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        QueuingSystem.LHYserver.SetPJXXResponse QueuingSystem.LHYserver.WebServiceSoap.SetPJXX(QueuingSystem.LHYserver.SetPJXXRequest request) {
            return base.Channel.SetPJXX(request);
        }
        
        public string SetPJXX(string dwjgdm, string dwmc, string yhbs, string yhxm, string qhxxxlh, string pjlb, string pjjg) {
            QueuingSystem.LHYserver.SetPJXXRequest inValue = new QueuingSystem.LHYserver.SetPJXXRequest();
            inValue.Body = new QueuingSystem.LHYserver.SetPJXXRequestBody();
            inValue.Body.dwjgdm = dwjgdm;
            inValue.Body.dwmc = dwmc;
            inValue.Body.yhbs = yhbs;
            inValue.Body.yhxm = yhxm;
            inValue.Body.qhxxxlh = qhxxxlh;
            inValue.Body.pjlb = pjlb;
            inValue.Body.pjjg = pjjg;
            QueuingSystem.LHYserver.SetPJXXResponse retVal = ((QueuingSystem.LHYserver.WebServiceSoap)(this)).SetPJXX(inValue);
            return retVal.Body.SetPJXXResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<QueuingSystem.LHYserver.SetPJXXResponse> QueuingSystem.LHYserver.WebServiceSoap.SetPJXXAsync(QueuingSystem.LHYserver.SetPJXXRequest request) {
            return base.Channel.SetPJXXAsync(request);
        }
        
        public System.Threading.Tasks.Task<QueuingSystem.LHYserver.SetPJXXResponse> SetPJXXAsync(string dwjgdm, string dwmc, string yhbs, string yhxm, string qhxxxlh, string pjlb, string pjjg) {
            QueuingSystem.LHYserver.SetPJXXRequest inValue = new QueuingSystem.LHYserver.SetPJXXRequest();
            inValue.Body = new QueuingSystem.LHYserver.SetPJXXRequestBody();
            inValue.Body.dwjgdm = dwjgdm;
            inValue.Body.dwmc = dwmc;
            inValue.Body.yhbs = yhbs;
            inValue.Body.yhxm = yhxm;
            inValue.Body.qhxxxlh = qhxxxlh;
            inValue.Body.pjlb = pjlb;
            inValue.Body.pjjg = pjjg;
            return ((QueuingSystem.LHYserver.WebServiceSoap)(this)).SetPJXXAsync(inValue);
        }
    }
}
